-- Views para consultas de remanejamentos UGR (UTFPR-CT)
-- Execute este script no SQL Editor do Supabase.

create schema if not exists utfprct;

create table if not exists utfprct.matrizcusteioaprovadact (
  id bigint generated by default as identity primary key,
  ugr text not null,
  gnd integer not null,
  valoraprovado numeric not null,
  created_at timestamp with time zone default now()
);

create or replace view utfprct.vw_matrizcusteioaprovadact as
select
  trim(ugr) as ugr,
  gnd,
  sum(coalesce(valoraprovado, 0))::numeric as valoraprovado
from utfprct.matrizcusteioaprovadact
group by trim(ugr), gnd;

create or replace view utfprct.vw_remanejamento_ugr_detalhado as
select
  id,
  ugr,
  tipo as tipo_recurso,
  gnd,
  fonte,
  valor,
  "Detalhes",
  data
from utfprct.remanejamento_ugr
where tipo in ('Despesas Gerais / Custeio', 'Arrecadação Própria');

create or replace view utfprct.vw_resultado_recurso_previsto_recebido_ugr as
with repassado as (
  select
    trim(ugr) as ugr,
    tipo as tipo_recurso,
    sum(valor)::numeric as valor_repassado
  from utfprct.remanejamento_ugr
  where tipo in ('Despesas Gerais / Custeio', 'Arrecadação Própria')
  group by trim(ugr), tipo
),
calculo_fatiado as (
  select
    rd.departamento,
    s.valor_total * coalesce(rd."UGR", 0::numeric) as fatia_departamento,
    s.valor_total * coalesce(rd."NIT", 0::numeric) as fatia_nit,
    s.valor_total * coalesce(rd."UTFPR", 0::numeric) as fatia_utfpr
  from sisgru.sisgru s
  join sisgru.referencia_departamento rd
    on s.numero_de_referencia = rd.referencia
  where s.data_de_pagamento is not null
),
arrecadacao_unificada as (
  select
    calculo_fatiado.departamento as nome_departamento,
    sum(calculo_fatiado.fatia_departamento)::numeric as total_arrecadado
  from calculo_fatiado
  group by calculo_fatiado.departamento
  union all
  select
    'NIT'::text as nome_departamento,
    sum(calculo_fatiado.fatia_nit)::numeric as total_arrecadado
  from calculo_fatiado
  union all
  select
    'UTFPR'::text as nome_departamento,
    sum(calculo_fatiado.fatia_utfpr)::numeric as total_arrecadado
  from calculo_fatiado
),
previsto_arrecadacao as (
  select
    trim(nome_departamento) as ugr,
    'Arrecadação Própria'::text as tipo_recurso,
    sum(coalesce(total_arrecadado, 0))::numeric as valor_previsto
  from arrecadacao_unificada
  group by trim(nome_departamento)
),
previsto_custeio as (
  select
    trim(ugr) as ugr,
    'Despesas Gerais / Custeio'::text as tipo_recurso,
    sum(coalesce(valoraprovado, 0))::numeric as valor_previsto
  from utfprct.vw_matrizcusteioaprovadact
  group by trim(ugr)
),
previsto as (
  select ugr, tipo_recurso, valor_previsto from previsto_arrecadacao
  union all
  select ugr, tipo_recurso, valor_previsto from previsto_custeio
),
chaves as (
  select ugr, tipo_recurso from repassado
  union
  select ugr, tipo_recurso from previsto
)
select
  c.ugr,
  c.tipo_recurso,
  coalesce(p.valor_previsto, 0) as valor_previsto,
  coalesce(r.valor_repassado, 0) as valor_repassado,
  coalesce(p.valor_previsto, 0) - coalesce(r.valor_repassado, 0) as valor_a_receber
from chaves c
left join repassado r
  on r.ugr = c.ugr
 and r.tipo_recurso = c.tipo_recurso
left join previsto p
  on p.ugr = c.ugr
 and p.tipo_recurso = c.tipo_recurso
order by c.ugr, c.tipo_recurso;
