-- Estrutura inicial: Matriz Orçamentária de Custeio UTFPR-CT
-- Execute no SQL Editor do Supabase

create schema if not exists utfprct;

create or replace function utfprct.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists utfprct.matriz_orc_departamentos (
  codigo text primary key,
  categoria text not null default 'DEPARTAMENTO',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_matriz_orc_departamentos_updated_at on utfprct.matriz_orc_departamentos;
create trigger trg_matriz_orc_departamentos_updated_at
before update on utfprct.matriz_orc_departamentos
for each row execute function utfprct.set_updated_at();

insert into utfprct.matriz_orc_departamentos (codigo, categoria)
values
  ('DACOC', 'DEPARTAMENTO'),
  ('DADIN', 'DEPARTAMENTO'),
  ('DAEFI', 'DEPARTAMENTO'),
  ('DAELN', 'DEPARTAMENTO'),
  ('DAELT', 'DEPARTAMENTO'),
  ('DAEST', 'DEPARTAMENTO'),
  ('DAFCH', 'DEPARTAMENTO'),
  ('DAFIS', 'DEPARTAMENTO'),
  ('DAGEE', 'DEPARTAMENTO'),
  ('DAINF', 'DEPARTAMENTO'),
  ('DALEM', 'DEPARTAMENTO'),
  ('DALIC', 'DEPARTAMENTO'),
  ('DAMAT', 'DEPARTAMENTO'),
  ('DAMEC', 'DEPARTAMENTO'),
  ('DAQBI', 'DEPARTAMENTO'),
  ('DEAAU', 'DEPARTAMENTO'),
  ('DAEDU', 'DEPARTAMENTO'),
  ('CPGEI', 'POS_GRADUACAO'),
  ('PPGA', 'POS_GRADUACAO'),
  ('PPGCA', 'POS_GRADUACAO'),
  ('PPGCTA', 'POS_GRADUACAO'),
  ('PPGDP', 'POS_GRADUACAO'),
  ('PPGEB', 'POS_GRADUACAO'),
  ('PPGEC', 'POS_GRADUACAO'),
  ('PPGEF', 'POS_GRADUACAO'),
  ('PPGEL', 'POS_GRADUACAO'),
  ('PPGEM', 'POS_GRADUACAO'),
  ('PPGET', 'POS_GRADUACAO'),
  ('PPGFA', 'POS_GRADUACAO'),
  ('PPGFCET', 'POS_GRADUACAO'),
  ('PPGPGP', 'POS_GRADUACAO'),
  ('PPGQ', 'POS_GRADUACAO'),
  ('PPGSAU', 'POS_GRADUACAO'),
  ('PPGSE', 'POS_GRADUACAO'),
  ('PPGTE', 'POS_GRADUACAO'),
  ('PROFIAP', 'POS_GRADUACAO'),
  ('PROFMAT', 'POS_GRADUACAO')
on conflict (codigo) do update
set categoria = excluded.categoria,
    updated_at = now();

create table if not exists utfprct.matriz_orc_dados_fixos (
  departamento text primary key references utfprct.matriz_orc_departamentos(codigo) on update cascade on delete restrict,
  v1_discentes numeric not null default 0,
  v2_docentes_ta numeric not null default 0,
  v3_titulacao numeric not null default 0,
  v4_estrutural numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_matriz_orc_dados_fixos_updated_at on utfprct.matriz_orc_dados_fixos;
create trigger trg_matriz_orc_dados_fixos_updated_at
before update on utfprct.matriz_orc_dados_fixos
for each row execute function utfprct.set_updated_at();

insert into utfprct.matriz_orc_dados_fixos (departamento)
select d.codigo
from utfprct.matriz_orc_departamentos d
where d.ativo = true
on conflict (departamento) do nothing;

create table if not exists utfprct.matriz_orc_simulacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  recurso_total numeric not null default 0,
  peso_v1 numeric not null default 25,
  peso_v2 numeric not null default 25,
  peso_v3 numeric not null default 25,
  peso_v4 numeric not null default 25,
  observacoes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_matriz_orc_simulacoes_updated_at on utfprct.matriz_orc_simulacoes;
create trigger trg_matriz_orc_simulacoes_updated_at
before update on utfprct.matriz_orc_simulacoes
for each row execute function utfprct.set_updated_at();

create table if not exists utfprct.matriz_orc_simulacao_departamentos (
  simulacao_id bigint not null references utfprct.matriz_orc_simulacoes(id) on update cascade on delete cascade,
  departamento text not null references utfprct.matriz_orc_departamentos(codigo) on update cascade on delete restrict,
  v1_discentes numeric not null default 0,
  v2_docentes_ta numeric not null default 0,
  v3_titulacao numeric not null default 0,
  v4_estrutural numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matriz_orc_simulacao_departamentos_pkey primary key (simulacao_id, departamento)
);

drop trigger if exists trg_matriz_orc_simulacao_departamentos_updated_at on utfprct.matriz_orc_simulacao_departamentos;
create trigger trg_matriz_orc_simulacao_departamentos_updated_at
before update on utfprct.matriz_orc_simulacao_departamentos
for each row execute function utfprct.set_updated_at();

create or replace view utfprct.vw_matriz_orc_base_departamentos as
select
  d.codigo as departamento,
  d.categoria,
  coalesce(f.v1_discentes, 0)::numeric as v1_discentes,
  coalesce(f.v2_docentes_ta, 0)::numeric as v2_docentes_ta,
  coalesce(f.v3_titulacao, 0)::numeric as v3_titulacao,
  coalesce(f.v4_estrutural, 0)::numeric as v4_estrutural
from utfprct.matriz_orc_departamentos d
left join utfprct.matriz_orc_dados_fixos f on f.departamento = d.codigo
where d.ativo = true
order by d.codigo;
