-- ─── CRONOGRAMA DE GASTOS (pág 12) ───────────────────────────────────────────
-- Plano de gastos por unidade por bimestre (limite = valor_estimado da matriz)
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_cronograma_gastos (
  id              bigint generated by default as identity primary key,
  configuracao_id bigint        NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id      bigint        NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  bimestre        int           NOT NULL CHECK (bimestre BETWEEN 1 AND 6),
  valor           numeric       NOT NULL DEFAULT 0 CHECK (valor >= 0),
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, unidade_id, bimestre)
);

CREATE TRIGGER trg_cronograma_gastos_upd
  BEFORE UPDATE ON utfprct.matriz_orc_cronograma_gastos
  FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- ─── REPASSE BIMESTRAL — CONFIGURAÇÃO (pág 13, aba 1) ────────────────────────
-- Valor disponível para repasse por bimestre (soma ≈ Recurso Líquido)
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_repasse_bimestral (
  id              bigint generated by default as identity primary key,
  configuracao_id bigint        NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  bimestre        int           NOT NULL CHECK (bimestre BETWEEN 1 AND 6),
  valor_disponivel numeric      NOT NULL DEFAULT 0 CHECK (valor_disponivel >= 0),
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, bimestre)
);

CREATE TRIGGER trg_repasse_bimestral_upd
  BEFORE UPDATE ON utfprct.matriz_orc_repasse_bimestral
  FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- ─── REPASSE BIMESTRAL — ITENS POR UNIDADE (pág 13, aba 1) ──────────────────
-- Valor calculado / enviado por unidade em cada bimestre
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_repasse_item (
  id              bigint generated by default as identity primary key,
  configuracao_id bigint        NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id      bigint        NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  bimestre        int           NOT NULL CHECK (bimestre BETWEEN 1 AND 6),
  valor_calculado numeric       NOT NULL DEFAULT 0,
  valor_enviado   numeric,                          -- NULL = ainda não enviado
  fixado          boolean       NOT NULL DEFAULT false,
  enviado         boolean       NOT NULL DEFAULT false,
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, unidade_id, bimestre)
);

CREATE TRIGGER trg_repasse_item_upd
  BEFORE UPDATE ON utfprct.matriz_orc_repasse_item
  FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- ─── REMANEJAMENTO INTERNO — CABEÇALHO (pág 13, aba 2) ───────────────────────
-- Cada evento de remanejamento com valor total disponível para distribuir
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_remanejamento (
  id              bigint generated by default as identity primary key,
  configuracao_id bigint        NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  descricao       text          NOT NULL DEFAULT '',
  valor_total     numeric       NOT NULL DEFAULT 0 CHECK (valor_total >= 0),
  data_referencia date,
  created_at      timestamptz   NOT NULL DEFAULT now(),
  updated_at      timestamptz   NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_remanejamento_upd
  BEFORE UPDATE ON utfprct.matriz_orc_remanejamento
  FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- ─── REMANEJAMENTO INTERNO — ITENS (pág 13, aba 2) ───────────────────────────
-- Distribuição por unidade para cada remanejamento
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_remanejamento_item (
  id               bigint generated by default as identity primary key,
  remanejamento_id bigint        NOT NULL REFERENCES utfprct.matriz_orc_remanejamento(id) ON DELETE CASCADE,
  unidade_id       bigint        NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  valor            numeric       NOT NULL DEFAULT 0,
  percentual       numeric       NOT NULL DEFAULT 0,  -- % do valor_total do remanejamento
  fixado           boolean       NOT NULL DEFAULT false,
  enviado          boolean       NOT NULL DEFAULT false,
  created_at       timestamptz   NOT NULL DEFAULT now(),
  updated_at       timestamptz   NOT NULL DEFAULT now(),
  UNIQUE (remanejamento_id, unidade_id)
);

CREATE TRIGGER trg_remanejamento_item_upd
  BEFORE UPDATE ON utfprct.matriz_orc_remanejamento_item
  FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();
