-- =============================================================================
-- MIGRAÇÃO INCREMENTAL: V1 Importação CSV
-- Execute APENAS este arquivo no SQL Editor do Supabase
-- Não re-executa o script completo — apenas adiciona as novas estruturas
-- =============================================================================

BEGIN;

-- Todas as colunas possivelmente ausentes em matriz_orc_simulacoes
ALTER TABLE utfprct.matriz_orc_simulacoes
  ADD COLUMN IF NOT EXISTS descricao              text,
  ADD COLUMN IF NOT EXISTS recurso_bruto          numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS recurso_liquido        numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pct_total              numeric NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS contratos_continuados  numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outras_despesas_campus numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seguranca_modo         text NOT NULL DEFAULT 'PERCENTUAL',
  ADD COLUMN IF NOT EXISTS seguranca_valor        numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS peso_v1                numeric NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS peso_v2                numeric NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS peso_v3                numeric NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS peso_v4                numeric NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS v1_peso_graduacao      numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS v1_peso_pos_graduacao  numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS v2_peso_docentes       numeric NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS v2_peso_taes           numeric NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS v2_peso_20h            numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v2_peso_40h            numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v2_peso_de             numeric NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS v2_peso_funcao_parcial numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v2_peso_funcao_integral numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v3_peso_graduacao      numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v3_peso_especializacao numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v3_peso_mestrado       numeric NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS v3_peso_doutorado      numeric NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS observacoes            text;

-- Todas as colunas possivelmente ausentes em matriz_orc_configuracao_base
ALTER TABLE utfprct.matriz_orc_configuracao_base
  ADD COLUMN IF NOT EXISTS recurso_bruto          numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS recurso_liquido        numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pct_total              numeric NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS contratos_continuados  numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outras_despesas_campus numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seguranca_modo         text NOT NULL DEFAULT 'PERCENTUAL',
  ADD COLUMN IF NOT EXISTS seguranca_valor        numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS peso_v1                numeric NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS peso_v2                numeric NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS peso_v3                numeric NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS peso_v4                numeric NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS v1_peso_graduacao      numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS v1_peso_pos_graduacao  numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS v2_peso_docentes       numeric NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS v2_peso_taes           numeric NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS v2_peso_20h            numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v2_peso_40h            numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v2_peso_de             numeric NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS v2_peso_funcao_parcial numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v2_peso_funcao_integral numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v3_peso_graduacao      numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS v3_peso_especializacao numeric NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS v3_peso_mestrado       numeric NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS v3_peso_doutorado      numeric NOT NULL DEFAULT 4;

-- Coluna de modo V1 na configuração
ALTER TABLE utfprct.matriz_orc_configuracao_base
  ADD COLUMN IF NOT EXISTS v1_modo text NOT NULL DEFAULT 'MANUAL'
    CHECK (v1_modo IN ('MANUAL', 'IMPORTADO'));

-- Tabela para linhas brutas importadas via CSV
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_v1_importacao (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  departamento    text,
  professor       text,
  disciplina      text,
  turma           text,
  nome_disc       text,
  cht             numeric(10,2) DEFAULT 0,
  nivel_ensino    text,
  quantidade_alunos integer DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_v1_importacao_cfg
  ON utfprct.matriz_orc_v1_importacao(configuracao_id);

-- View que agrega dados importados no mesmo formato de matriz_orc_v1_unidade
-- Regra de nível: 'G', 'GRAD' ou contém 'gradua' → Graduação; demais → Pós
-- Situações ignoradas: cancelada, inativa, desativada
-- Classificação por nivel_ensino do CSV:
--   'Ensino Superior' → CH Grad + Alunos Grad
--   'Stricto Sensu'   → CH Pós  + Alunos Pós
-- Sem filtro de situacao_turma — todos os registros são contabilizados
DROP VIEW IF EXISTS utfprct.vw_matriz_orc_v1_importado CASCADE;
CREATE VIEW utfprct.vw_matriz_orc_v1_importado AS
SELECT
  i.configuracao_id,
  u.id   AS unidade_id,
  u.sigla,
  u.nome,
  u.tipo,
  SUM(CASE WHEN i.nivel_ensino = 'Ensino Superior' THEN i.cht              ELSE 0 END) AS carga_horaria_graduacao,
  SUM(CASE WHEN i.nivel_ensino = 'Stricto Sensu'   THEN i.cht              ELSE 0 END) AS carga_horaria_pos,
  SUM(CASE WHEN i.nivel_ensino = 'Ensino Superior' THEN i.quantidade_alunos ELSE 0 END) AS alunos_graduacao,
  SUM(CASE WHEN i.nivel_ensino = 'Stricto Sensu'   THEN i.quantidade_alunos ELSE 0 END) AS alunos_pos,
  COALESCE(MAX(man.peso_unidade), 1.0)::numeric AS peso_unidade
FROM utfprct.matriz_orc_v1_importacao i
JOIN utfprct.matriz_orc_unidades u
  ON UPPER(TRIM(u.sigla)) = UPPER(TRIM(i.departamento))
LEFT JOIN utfprct.matriz_orc_v1_unidade man
  ON man.unidade_id = u.id AND man.configuracao_id = i.configuracao_id
GROUP BY i.configuracao_id, u.id, u.sigla, u.nome, u.tipo;

-- View: departamentos importados que não têm correspondência em unidades cadastradas
DROP VIEW IF EXISTS utfprct.vw_v1_departamentos_nao_reconhecidos;
CREATE VIEW utfprct.vw_v1_departamentos_nao_reconhecidos AS
SELECT
  i.configuracao_id,
  c.ano,
  i.departamento,
  COUNT(*) AS total_linhas,
  SUM(i.quantidade_alunos) AS total_alunos,
  SUM(i.cht) AS total_cht
FROM utfprct.matriz_orc_v1_importacao i
JOIN utfprct.matriz_orc_configuracao_base c ON c.id = i.configuracao_id
WHERE NOT EXISTS (
  SELECT 1 FROM utfprct.matriz_orc_unidades u
  WHERE UPPER(TRIM(u.sigla)) = UPPER(TRIM(i.departamento))
)
GROUP BY i.configuracao_id, c.ano, i.departamento
ORDER BY c.ano DESC, i.departamento;

-- Remove coluna situacao_turma (não utilizada na view)
ALTER TABLE utfprct.matriz_orc_v1_importacao
  DROP COLUMN IF EXISTS situacao_turma;

-- Atualiza vw_matriz_orc_resultado para respeitar v1_modo:
--   MANUAL    → lê de matriz_orc_v1_unidade (comportamento original)
--   IMPORTADO → lê CH/alunos de vw_matriz_orc_v1_importado + peso_unidade de matriz_orc_v1_unidade
CREATE OR REPLACE VIEW utfprct.vw_matriz_orc_resultado AS
WITH cfg AS (
  SELECT * FROM utfprct.matriz_orc_configuracao_base WHERE ativo = true ORDER BY id DESC LIMIT 1
),
v1_fonte AS (
  SELECT
    imp.unidade_id,
    imp.configuracao_id,
    imp.carga_horaria_graduacao,
    imp.carga_horaria_pos,
    imp.alunos_graduacao,
    imp.alunos_pos,
    COALESCE(man.peso_unidade, 1.0) AS peso_unidade
  FROM utfprct.vw_matriz_orc_v1_importado imp
  JOIN cfg ON imp.configuracao_id = cfg.id AND cfg.v1_modo = 'IMPORTADO'
  LEFT JOIN utfprct.matriz_orc_v1_unidade man
    ON man.unidade_id = imp.unidade_id AND man.configuracao_id = cfg.id
  UNION ALL
  SELECT
    v.unidade_id,
    v.configuracao_id,
    v.carga_horaria_graduacao,
    v.carga_horaria_pos,
    v.alunos_graduacao,
    v.alunos_pos,
    v.peso_unidade
  FROM utfprct.matriz_orc_v1_unidade v
  JOIN cfg ON v.configuracao_id = cfg.id AND cfg.v1_modo = 'MANUAL'
),
v1 AS (
  SELECT
    f.unidade_id,
    f.configuracao_id,
    (
      (f.carga_horaria_graduacao * f.alunos_graduacao * cfg.v1_peso_graduacao / 100.0)
      + (f.carga_horaria_pos * f.alunos_pos * cfg.v1_peso_pos_graduacao / 100.0)
    ) * f.peso_unidade AS score
  FROM v1_fonte f, cfg
),
v2 AS (
  SELECT
    v.unidade_id,
    (
      (v.docentes_20h * cfg.v2_peso_20h + v.docentes_40h * cfg.v2_peso_40h + v.docentes_de * cfg.v2_peso_de) * cfg.v2_peso_docentes / 100.0
      + (v.taes_parcial * cfg.v2_peso_funcao_parcial + v.taes_integral * cfg.v2_peso_funcao_integral) * cfg.v2_peso_taes / 100.0
      + (v.docentes_funcao_parcial * cfg.v2_peso_funcao_parcial + v.docentes_funcao_integral * cfg.v2_peso_funcao_integral) * cfg.v2_peso_docentes / 100.0
    ) AS score
  FROM utfprct.matriz_orc_v2_unidade v, cfg WHERE v.configuracao_id = cfg.id
),
v3 AS (
  SELECT
    v.unidade_id,
    (
      v.docentes_graduacao * cfg.v3_peso_graduacao
      + v.docentes_especializacao * cfg.v3_peso_especializacao
      + v.docentes_mestrado * cfg.v3_peso_mestrado
      + v.docentes_doutorado * cfg.v3_peso_doutorado
    ) AS score
  FROM utfprct.matriz_orc_v3_unidade v, cfg WHERE v.configuracao_id = cfg.id
),
v4_raw AS (
  SELECT
    e.unidade_id,
    SUM(COALESCE(a.peso,0) * COALESCE(t.peso,0)) AS score
  FROM utfprct.matriz_orc_estruturas e
  JOIN utfprct.matriz_orc_estrutura_tipos t ON t.id = e.tipo_id
  JOIN utfprct.matriz_orc_estrutura_selecao sel ON sel.estrutura_id = e.id
  JOIN utfprct.matriz_orc_estrutura_atributos a ON a.id = sel.atributo_id
  JOIN cfg ON e.configuracao_id = cfg.id AND e.ativo = true
  GROUP BY e.unidade_id
),
combined AS (
  SELECT
    u.id AS unidade_id,
    u.sigla,
    u.nome,
    u.tipo,
    cfg.id AS configuracao_id,
    cfg.peso_v1, cfg.peso_v2, cfg.peso_v3, cfg.peso_v4,
    COALESCE(v1.score, 0) AS score_v1,
    COALESCE(v2.score, 0) AS score_v2,
    COALESCE(v3.score, 0) AS score_v3,
    COALESCE(v4_raw.score, 0) AS score_v4
  FROM utfprct.matriz_orc_unidades u
  CROSS JOIN cfg
  LEFT JOIN v1 ON v1.unidade_id = u.id
  LEFT JOIN v2 ON v2.unidade_id = u.id
  LEFT JOIN v3 ON v3.unidade_id = u.id
  LEFT JOIN v4_raw ON v4_raw.unidade_id = u.id
  WHERE u.ativo = true
),
totais AS (
  SELECT
    configuracao_id,
    SUM(score_v1) AS total_v1,
    SUM(score_v2) AS total_v2,
    SUM(score_v3) AS total_v3,
    SUM(score_v4) AS total_v4
  FROM combined GROUP BY configuracao_id
),
indice AS (
  SELECT
    c.*,
    t.total_v1, t.total_v2, t.total_v3, t.total_v4,
    CASE WHEN t.total_v1 > 0 THEN c.score_v1 / t.total_v1 ELSE 0 END AS idx_v1,
    CASE WHEN t.total_v2 > 0 THEN c.score_v2 / t.total_v2 ELSE 0 END AS idx_v2,
    CASE WHEN t.total_v3 > 0 THEN c.score_v3 / t.total_v3 ELSE 0 END AS idx_v3,
    CASE WHEN t.total_v4 > 0 THEN c.score_v4 / t.total_v4 ELSE 0 END AS idx_v4,
    NULLIF(
      CASE WHEN t.total_v1 > 0 THEN c.peso_v1 ELSE 0 END
      + CASE WHEN t.total_v2 > 0 THEN c.peso_v2 ELSE 0 END
      + CASE WHEN t.total_v3 > 0 THEN c.peso_v3 ELSE 0 END
      + CASE WHEN t.total_v4 > 0 THEN c.peso_v4 ELSE 0 END, 0
    ) AS active_w_sum
  FROM combined c JOIN totais t ON t.configuracao_id = c.configuracao_id
)
SELECT
  i.unidade_id,
  i.sigla,
  i.nome,
  i.tipo,
  i.score_v1, i.score_v2, i.score_v3, i.score_v4,
  COALESCE(
    ( CASE WHEN i.total_v1 > 0 THEN i.idx_v1 * i.peso_v1 ELSE 0 END
    + CASE WHEN i.total_v2 > 0 THEN i.idx_v2 * i.peso_v2 ELSE 0 END
    + CASE WHEN i.total_v3 > 0 THEN i.idx_v3 * i.peso_v3 ELSE 0 END
    + CASE WHEN i.total_v4 > 0 THEN i.idx_v4 * i.peso_v4 ELSE 0 END
    ) / i.active_w_sum, 0
  ) AS indice_composto,
  cfg.recurso_bruto,
  cfg.recurso_liquido,
  cfg.pct_total,
  cfg.recurso_liquido * cfg.pct_total / 100.0 AS valor_base,
  COALESCE(
    ( CASE WHEN i.total_v1 > 0 THEN i.idx_v1 * i.peso_v1 ELSE 0 END
    + CASE WHEN i.total_v2 > 0 THEN i.idx_v2 * i.peso_v2 ELSE 0 END
    + CASE WHEN i.total_v3 > 0 THEN i.idx_v3 * i.peso_v3 ELSE 0 END
    + CASE WHEN i.total_v4 > 0 THEN i.idx_v4 * i.peso_v4 ELSE 0 END
    ) / i.active_w_sum, 0
  ) * cfg.recurso_liquido * cfg.pct_total / 100.0 AS valor_estimado
FROM indice i, cfg;

COMMIT;
