-- =============================================================================
-- MIGRAÇÃO: Unidades Fixas (tipo_valor), Valores Fixos por Config e Overrides de Simulação
-- Execute APENAS este arquivo no SQL Editor do Supabase
-- =============================================================================

BEGIN;

-- 1. Adicionar tipo_valor em matriz_orc_unidades (padrão: CALCULADO)
ALTER TABLE utfprct.matriz_orc_unidades
  ADD COLUMN IF NOT EXISTS tipo_valor VARCHAR(10) NOT NULL DEFAULT 'CALCULADO';

-- Garantir que registros existentes tenham o valor padrão
UPDATE utfprct.matriz_orc_unidades
  SET tipo_valor = 'CALCULADO'
  WHERE tipo_valor IS NULL OR tipo_valor NOT IN ('CALCULADO', 'FIXO');

-- 2. Tabela de valores fixos por unidade por configuração
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_valores_fixos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id BIGINT NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id      BIGINT NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  valor_fixo      NUMERIC(15,2) NOT NULL DEFAULT 0,
  UNIQUE (configuracao_id, unidade_id)
);

CREATE INDEX IF NOT EXISTS idx_valores_fixos_cfg
  ON utfprct.matriz_orc_valores_fixos(configuracao_id);

-- 3. Tabela de overrides fixo/calculado por simulação (sobrescreve o tipo_valor da unidade)
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_sim_unidade_override (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  simulacao_id BIGINT NOT NULL REFERENCES utfprct.matriz_orc_simulacoes(id) ON DELETE CASCADE,
  unidade_id   BIGINT NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  tipo_valor   VARCHAR(10) NOT NULL DEFAULT 'CALCULADO',
  valor_fixo   NUMERIC(15,2) NOT NULL DEFAULT 0,
  UNIQUE (simulacao_id, unidade_id)
);

CREATE INDEX IF NOT EXISTS idx_sim_override_sim
  ON utfprct.matriz_orc_sim_unidade_override(simulacao_id);

COMMIT;
