-- =============================================================================
-- MIGRAÇÃO COMPLETA: Matriz Orçamentária de Custeio UTFPR-CT
-- Execute no SQL Editor do Supabase (idempotente)
-- =============================================================================

BEGIN;

-- Garantir schema
CREATE SCHEMA IF NOT EXISTS utfprct;

-- Função updated_at
CREATE OR REPLACE FUNCTION utfprct.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN new.updated_at = now(); RETURN new; END; $$;

-- -----------------------------------------------------------------------------
-- REMOÇÃO DE TABELAS ANTIGAS (ordem inversa de dependência)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS utfprct.matriz_orc_simulacao_departamentos CASCADE;
DROP VIEW IF EXISTS utfprct.vw_matriz_orc_base_departamentos;
DROP TABLE IF EXISTS utfprct.matriz_orc_dados_fixos CASCADE;
DROP TABLE IF EXISTS utfprct.matriz_orc_departamentos CASCADE;

-- -----------------------------------------------------------------------------
-- CAMPI
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_campi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sigla text NOT NULL UNIQUE,
  nome text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_matriz_orc_campi_upd ON utfprct.matriz_orc_campi;
CREATE TRIGGER trg_matriz_orc_campi_upd BEFORE UPDATE ON utfprct.matriz_orc_campi FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();
INSERT INTO utfprct.matriz_orc_campi (sigla, nome) VALUES ('CT', 'Curitiba') ON CONFLICT (sigla) DO NOTHING;

-- -----------------------------------------------------------------------------
-- SEDES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_sedes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id bigint NOT NULL REFERENCES utfprct.matriz_orc_campi(id) ON DELETE CASCADE,
  nome text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campus_id, nome)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_sedes_upd ON utfprct.matriz_orc_sedes;
CREATE TRIGGER trg_matriz_orc_sedes_upd BEFORE UPDATE ON utfprct.matriz_orc_sedes FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();
INSERT INTO utfprct.matriz_orc_sedes (campus_id, nome)
  SELECT c.id, s.nome FROM utfprct.matriz_orc_campi c
  CROSS JOIN (VALUES ('Centro'), ('Neoville'), ('Ecoville')) AS s(nome)
  WHERE c.sigla = 'CT'
  ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- UNIDADES (antigo departamentos)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_unidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campus_id bigint NOT NULL REFERENCES utfprct.matriz_orc_campi(id),
  sede_id bigint REFERENCES utfprct.matriz_orc_sedes(id),
  sigla text NOT NULL,
  nome text NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('GRADUACAO','POS_GRADUACAO','ADMINISTRATIVO','GESTAO_DIRETORIA')),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (campus_id, sigla)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_unidades_upd ON utfprct.matriz_orc_unidades;
CREATE TRIGGER trg_matriz_orc_unidades_upd BEFORE UPDATE ON utfprct.matriz_orc_unidades FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- Seed: unidades de graduação
INSERT INTO utfprct.matriz_orc_unidades (campus_id, sede_id, sigla, nome, tipo)
SELECT c.id, s.id, u.sigla, u.nome, u.tipo
FROM utfprct.matriz_orc_campi c
JOIN utfprct.matriz_orc_sedes s ON s.campus_id = c.id AND s.nome = 'Sede Central'
CROSS JOIN (VALUES
  ('DACOC','Depto. Acadêmico de Construção Civil','GRADUACAO'),
  ('DADIN','Depto. Acadêmico de Desenho Industrial','GRADUACAO'),
  ('DAEFI','Depto. Acadêmico de Educação Física','GRADUACAO'),
  ('DAELN','Depto. Acadêmico de Eletrônica','GRADUACAO'),
  ('DAELT','Depto. Acadêmico de Eletrotécnica','GRADUACAO'),
  ('DAEST','Depto. Acadêmico de Estruturas e Construção Civil','GRADUACAO'),
  ('DAFCH','Depto. Acadêmico de Formação Geral','GRADUACAO'),
  ('DAFIS','Depto. Acadêmico de Física','GRADUACAO'),
  ('DAGEE','Depto. Acadêmico de Engenharia Elétrica','GRADUACAO'),
  ('DAINF','Depto. Acadêmico de Informática','GRADUACAO'),
  ('DALEM','Depto. Acadêmico de Linguagens e Comunicação','GRADUACAO'),
  ('DALIC','Depto. Acadêmico de Licenciatura','GRADUACAO'),
  ('DAMAT','Depto. Acadêmico de Matemática','GRADUACAO'),
  ('DAMEC','Depto. Acadêmico de Mecânica','GRADUACAO'),
  ('DAQBI','Depto. Acadêmico de Química e Biologia','GRADUACAO'),
  ('DEAAU','Depto. Acadêmico de Arquitetura e Urbanismo','GRADUACAO'),
  ('DAEDU','Depto. Acadêmico de Educação','GRADUACAO'),
  ('CPGEI','Prog. Interdisciplinar em Eng. e Ciência','POS_GRADUACAO'),
  ('PPGA','Prog. de Pós-Graduação em Administração','POS_GRADUACAO'),
  ('PPGCA','Prog. de Pós-Graduação em Computação Aplicada','POS_GRADUACAO'),
  ('PPGCTA','Prog. de Pós-Graduação em Ciência e Tecnologia Ambiental','POS_GRADUACAO'),
  ('PPGDP','Prog. de Pós-Graduação em Dispositivos e Sistemas Físicos','POS_GRADUACAO'),
  ('PPGEB','Prog. de Pós-Graduação em Engenharia Biomédica','POS_GRADUACAO'),
  ('PPGEC','Prog. de Pós-Graduação em Engenharia Civil','POS_GRADUACAO'),
  ('PPGEF','Prog. de Pós-Graduação em Engenharia de Fabricação','POS_GRADUACAO'),
  ('PPGEL','Prog. de Pós-Graduação em Engenharia Elétrica e Informática Industrial','POS_GRADUACAO'),
  ('PPGEM','Prog. de Pós-Graduação em Engenharia Mecânica e de Materiais','POS_GRADUACAO'),
  ('PPGET','Prog. de Pós-Graduação em Engenharia de Telecomunicações','POS_GRADUACAO'),
  ('PPGFA','Prog. de Pós-Graduação em Física Aplicada','POS_GRADUACAO'),
  ('PPGFCET','Prog. de Pós-Graduação em Formação Científica, Educacional e Tecnológica','POS_GRADUACAO'),
  ('PPGPGP','Prog. de Pós-Graduação em Planejamento e Governança Pública','POS_GRADUACAO'),
  ('PPGQ','Prog. de Pós-Graduação em Química','POS_GRADUACAO'),
  ('PPGSAU','Prog. de Pós-Graduação em Saúde e Tecnologia','POS_GRADUACAO'),
  ('PPGSE','Prog. de Pós-Graduação em Sistemas de Energia','POS_GRADUACAO'),
  ('PPGTE','Prog. de Pós-Graduação em Tecnologia e Sociedade','POS_GRADUACAO'),
  ('PROFIAP','PROFIAP','POS_GRADUACAO'),
  ('PROFMAT','PROFMAT','POS_GRADUACAO')
) AS u(sigla, nome, tipo)
WHERE c.sigla = 'CT'
ON CONFLICT (campus_id, sigla) DO NOTHING;

-- -----------------------------------------------------------------------------
-- CONFIGURAÇÃO BASE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_configuracao_base (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano integer NOT NULL DEFAULT EXTRACT(YEAR FROM now())::integer,
  descricao text,
  recurso_bruto numeric NOT NULL DEFAULT 0,
  recurso_liquido numeric NOT NULL DEFAULT 0,
  pct_total numeric NOT NULL DEFAULT 100,
  -- Pesos das variáveis (%)
  peso_v1 numeric NOT NULL DEFAULT 20,
  peso_v2 numeric NOT NULL DEFAULT 30,
  peso_v3 numeric NOT NULL DEFAULT 25,
  peso_v4 numeric NOT NULL DEFAULT 25,
  -- Contratos continuados e despesas
  contratos_continuados numeric NOT NULL DEFAULT 0,
  outras_despesas_campus numeric NOT NULL DEFAULT 0,
  -- Segurança
  seguranca_modo text NOT NULL DEFAULT 'PERCENTUAL' CHECK (seguranca_modo IN ('PERCENTUAL','FIXO')),
  seguranca_valor numeric NOT NULL DEFAULT 0,
  -- Sub-pesos V1
  v1_peso_graduacao numeric NOT NULL DEFAULT 50,
  v1_peso_pos_graduacao numeric NOT NULL DEFAULT 50,
  -- Sub-pesos V2
  v2_peso_docentes numeric NOT NULL DEFAULT 60,
  v2_peso_taes numeric NOT NULL DEFAULT 40,
  v2_peso_20h numeric NOT NULL DEFAULT 1,
  v2_peso_40h numeric NOT NULL DEFAULT 2,
  v2_peso_de numeric NOT NULL DEFAULT 3,
  v2_peso_funcao_parcial numeric NOT NULL DEFAULT 1,
  v2_peso_funcao_integral numeric NOT NULL DEFAULT 2,
  -- Sub-pesos V3
  v3_peso_graduacao numeric NOT NULL DEFAULT 1,
  v3_peso_especializacao numeric NOT NULL DEFAULT 2,
  v3_peso_mestrado numeric NOT NULL DEFAULT 3,
  v3_peso_doutorado numeric NOT NULL DEFAULT 4,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_matriz_orc_config_upd ON utfprct.matriz_orc_configuracao_base;
CREATE TRIGGER trg_matriz_orc_config_upd BEFORE UPDATE ON utfprct.matriz_orc_configuracao_base FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- V1 - DADOS POR UNIDADE (DISCENTES)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_v1_unidade (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id bigint NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  carga_horaria_graduacao numeric NOT NULL DEFAULT 0,
  carga_horaria_pos numeric NOT NULL DEFAULT 0,
  alunos_graduacao numeric NOT NULL DEFAULT 0,
  alunos_pos numeric NOT NULL DEFAULT 0,
  peso_unidade numeric NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, unidade_id)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_v1_upd ON utfprct.matriz_orc_v1_unidade;
CREATE TRIGGER trg_matriz_orc_v1_upd BEFORE UPDATE ON utfprct.matriz_orc_v1_unidade FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- V2 - DADOS POR UNIDADE (DOCENTES E TAEs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_v2_unidade (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id bigint NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  docentes_20h integer NOT NULL DEFAULT 0,
  docentes_40h integer NOT NULL DEFAULT 0,
  docentes_de integer NOT NULL DEFAULT 0,
  taes_parcial integer NOT NULL DEFAULT 0,
  taes_integral integer NOT NULL DEFAULT 0,
  docentes_funcao_parcial integer NOT NULL DEFAULT 0,
  docentes_funcao_integral integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, unidade_id)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_v2_upd ON utfprct.matriz_orc_v2_unidade;
CREATE TRIGGER trg_matriz_orc_v2_upd BEFORE UPDATE ON utfprct.matriz_orc_v2_unidade FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- V3 - DADOS POR UNIDADE (TITULAÇÃO DOCENTE)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_v3_unidade (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id bigint NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  docentes_graduacao integer NOT NULL DEFAULT 0,
  docentes_especializacao integer NOT NULL DEFAULT 0,
  docentes_mestrado integer NOT NULL DEFAULT 0,
  docentes_doutorado integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (configuracao_id, unidade_id)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_v3_upd ON utfprct.matriz_orc_v3_unidade;
CREATE TRIGGER trg_matriz_orc_v3_upd BEFORE UPDATE ON utfprct.matriz_orc_v3_unidade FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- V4 - TIPOS DE ESTRUTURA
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_estrutura_tipos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL UNIQUE,
  peso numeric NOT NULL DEFAULT 1,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_matriz_orc_etipo_upd ON utfprct.matriz_orc_estrutura_tipos;
CREATE TRIGGER trg_matriz_orc_etipo_upd BEFORE UPDATE ON utfprct.matriz_orc_estrutura_tipos FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();
INSERT INTO utfprct.matriz_orc_estrutura_tipos (nome, peso) VALUES ('Laboratório', 1) ON CONFLICT (nome) DO NOTHING;

-- -----------------------------------------------------------------------------
-- V4 - CLASSES DE ATRIBUTOS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_estrutura_classes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_id bigint NOT NULL REFERENCES utfprct.matriz_orc_estrutura_tipos(id) ON DELETE CASCADE,
  nome text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tipo_id, nome)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_eclass_upd ON utfprct.matriz_orc_estrutura_classes;
CREATE TRIGGER trg_matriz_orc_eclass_upd BEFORE UPDATE ON utfprct.matriz_orc_estrutura_classes FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

INSERT INTO utfprct.matriz_orc_estrutura_classes (tipo_id, nome)
SELECT t.id, c.nome FROM utfprct.matriz_orc_estrutura_tipos t
CROSS JOIN (VALUES
  ('Material de Consumo Utilizado'),
  ('Manutenção dos Equipamentos'),
  ('Durabilidade do Ferramental'),
  ('Utilização do Laboratório')
) AS c(nome) WHERE t.nome = 'Laboratório'
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- V4 - ATRIBUTOS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_estrutura_atributos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classe_id bigint NOT NULL REFERENCES utfprct.matriz_orc_estrutura_classes(id) ON DELETE CASCADE,
  descricao text NOT NULL,
  peso numeric NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (classe_id, descricao)
);
DROP TRIGGER IF EXISTS trg_matriz_orc_eattr_upd ON utfprct.matriz_orc_estrutura_atributos;
CREATE TRIGGER trg_matriz_orc_eattr_upd BEFORE UPDATE ON utfprct.matriz_orc_estrutura_atributos FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

INSERT INTO utfprct.matriz_orc_estrutura_atributos (classe_id, descricao, peso)
SELECT cl.id, a.descricao, a.peso
FROM utfprct.matriz_orc_estrutura_classes cl
JOIN utfprct.matriz_orc_estrutura_tipos t ON t.id = cl.tipo_id AND t.nome = 'Laboratório'
CROSS JOIN (VALUES
  ('Material de Consumo Utilizado','Totalmente do Almoxarifado',1),
  ('Material de Consumo Utilizado','Apenas alguns itens do almoxarifado',3),
  ('Material de Consumo Utilizado','Materiais fora de estoque',6),
  ('Manutenção dos Equipamentos','UTFPR e Serviços Contratados',3),
  ('Manutenção dos Equipamentos','Totalmente por Contratação de Serviço',6),
  ('Durabilidade do Ferramental','Curta',3),
  ('Durabilidade do Ferramental','Média',2),
  ('Durabilidade do Ferramental','Grande',1),
  ('Utilização do Laboratório','Exclusivo do Departamento',1),
  ('Utilização do Laboratório','Compartilhado com demais departamentos',2)
) AS a(classe_nome, descricao, peso)
WHERE cl.nome = a.classe_nome
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- V4 - ESTRUTURAS (instâncias cadastradas por unidade)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_estruturas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  unidade_id bigint NOT NULL REFERENCES utfprct.matriz_orc_unidades(id) ON DELETE CASCADE,
  tipo_id bigint NOT NULL REFERENCES utfprct.matriz_orc_estrutura_tipos(id),
  nome text NOT NULL,
  sede_id bigint REFERENCES utfprct.matriz_orc_sedes(id),
  sala text,
  responsavel_nome text,
  responsavel_email text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_matriz_orc_estruturas_upd ON utfprct.matriz_orc_estruturas;
CREATE TRIGGER trg_matriz_orc_estruturas_upd BEFORE UPDATE ON utfprct.matriz_orc_estruturas FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- V4 - ATRIBUTOS SELECIONADOS POR ESTRUTURA
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_estrutura_selecao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estrutura_id bigint NOT NULL REFERENCES utfprct.matriz_orc_estruturas(id) ON DELETE CASCADE,
  atributo_id bigint NOT NULL REFERENCES utfprct.matriz_orc_estrutura_atributos(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (estrutura_id, atributo_id)
);

-- -----------------------------------------------------------------------------
-- SIMULAÇÕES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_simulacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE SET NULL,
  nome text NOT NULL,
  descricao text,
  recurso_bruto numeric NOT NULL DEFAULT 0,
  recurso_liquido numeric NOT NULL DEFAULT 0,
  pct_total numeric NOT NULL DEFAULT 100,
  contratos_continuados numeric NOT NULL DEFAULT 0,
  outras_despesas_campus numeric NOT NULL DEFAULT 0,
  seguranca_modo text NOT NULL DEFAULT 'PERCENTUAL' CHECK (seguranca_modo IN ('PERCENTUAL','FIXO')),
  seguranca_valor numeric NOT NULL DEFAULT 0,
  peso_v1 numeric NOT NULL DEFAULT 20,
  peso_v2 numeric NOT NULL DEFAULT 30,
  peso_v3 numeric NOT NULL DEFAULT 25,
  peso_v4 numeric NOT NULL DEFAULT 25,
  v1_peso_graduacao numeric NOT NULL DEFAULT 50,
  v1_peso_pos_graduacao numeric NOT NULL DEFAULT 50,
  v2_peso_docentes numeric NOT NULL DEFAULT 60,
  v2_peso_taes numeric NOT NULL DEFAULT 40,
  v2_peso_20h numeric NOT NULL DEFAULT 1,
  v2_peso_40h numeric NOT NULL DEFAULT 2,
  v2_peso_de numeric NOT NULL DEFAULT 3,
  v2_peso_funcao_parcial numeric NOT NULL DEFAULT 1,
  v2_peso_funcao_integral numeric NOT NULL DEFAULT 2,
  v3_peso_graduacao numeric NOT NULL DEFAULT 1,
  v3_peso_especializacao numeric NOT NULL DEFAULT 2,
  v3_peso_mestrado numeric NOT NULL DEFAULT 3,
  v3_peso_doutorado numeric NOT NULL DEFAULT 4,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_matriz_orc_simulacoes_upd ON utfprct.matriz_orc_simulacoes;
CREATE TRIGGER trg_matriz_orc_simulacoes_upd BEFORE UPDATE ON utfprct.matriz_orc_simulacoes FOR EACH ROW EXECUTE FUNCTION utfprct.set_updated_at();

-- -----------------------------------------------------------------------------
-- VIEW: resultado calculado por unidade
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW utfprct.vw_matriz_orc_resultado AS
WITH cfg AS (
  SELECT * FROM utfprct.matriz_orc_configuracao_base WHERE ativo = true ORDER BY id DESC LIMIT 1
),
v1 AS (
  SELECT
    v.unidade_id,
    v.configuracao_id,
    (
      (v.carga_horaria_graduacao * v.alunos_graduacao * cfg.v1_peso_graduacao / 100.0)
      + (v.carga_horaria_pos * v.alunos_pos * cfg.v1_peso_pos_graduacao / 100.0)
    ) * v.peso_unidade AS score
  FROM utfprct.matriz_orc_v1_unidade v, cfg WHERE v.configuracao_id = cfg.id
),
v2 AS (
  SELECT
    v.unidade_id,
    (
      (v.docentes_20h * cfg.v2_peso_20h + v.docentes_40h * cfg.v2_peso_40h + v.docentes_de * cfg.v2_peso_de) * cfg.v2_peso_docentes / 100.0
      + (v.taes_parcial * cfg.v2_peso_funcao_parcial + v.taes_integral * cfg.v2_peso_funcao_integral) * cfg.v2_peso_taes / 100.0
      + (v.docentes_funcao_parcial * cfg.v2_peso_funcao_parcial + v.docentes_funcao_integral * cfg.v2_peso_funcao_integral) * cfg.v2_peso_docentes / 100.0
    ) AS score
  FROM utfprct.matriz_orc_v2_unidade v, cfg WHERE v.configuracao_id = cfg.id
),
v3 AS (
  SELECT
    v.unidade_id,
    (
      v.docentes_graduacao * cfg.v3_peso_graduacao
      + v.docentes_especializacao * cfg.v3_peso_especializacao
      + v.docentes_mestrado * cfg.v3_peso_mestrado
      + v.docentes_doutorado * cfg.v3_peso_doutorado
    ) AS score
  FROM utfprct.matriz_orc_v3_unidade v, cfg WHERE v.configuracao_id = cfg.id
),
v4_raw AS (
  SELECT
    e.unidade_id,
    SUM(COALESCE(a.peso,0) * COALESCE(t.peso,0)) AS score
  FROM utfprct.matriz_orc_estruturas e
  JOIN utfprct.matriz_orc_estrutura_tipos t ON t.id = e.tipo_id
  JOIN utfprct.matriz_orc_estrutura_selecao sel ON sel.estrutura_id = e.id
  JOIN utfprct.matriz_orc_estrutura_atributos a ON a.id = sel.atributo_id
  JOIN cfg ON e.configuracao_id = cfg.id AND e.ativo = true
  GROUP BY e.unidade_id
),
combined AS (
  SELECT
    u.id AS unidade_id,
    u.sigla,
    u.nome,
    u.tipo,
    cfg.id AS configuracao_id,
    cfg.peso_v1, cfg.peso_v2, cfg.peso_v3, cfg.peso_v4,
    COALESCE(v1.score, 0) AS score_v1,
    COALESCE(v2.score, 0) AS score_v2,
    COALESCE(v3.score, 0) AS score_v3,
    COALESCE(v4_raw.score, 0) AS score_v4
  FROM utfprct.matriz_orc_unidades u
  CROSS JOIN cfg
  LEFT JOIN v1 ON v1.unidade_id = u.id
  LEFT JOIN v2 ON v2.unidade_id = u.id
  LEFT JOIN v3 ON v3.unidade_id = u.id
  LEFT JOIN v4_raw ON v4_raw.unidade_id = u.id
  WHERE u.ativo = true
),
totais AS (
  SELECT
    configuracao_id,
    SUM(score_v1) AS total_v1,
    SUM(score_v2) AS total_v2,
    SUM(score_v3) AS total_v3,
    SUM(score_v4) AS total_v4
  FROM combined GROUP BY configuracao_id
),
indice AS (
  SELECT
    c.*,
    t.total_v1, t.total_v2, t.total_v3, t.total_v4,
    CASE WHEN t.total_v1 > 0 THEN c.score_v1 / t.total_v1 ELSE 0 END AS idx_v1,
    CASE WHEN t.total_v2 > 0 THEN c.score_v2 / t.total_v2 ELSE 0 END AS idx_v2,
    CASE WHEN t.total_v3 > 0 THEN c.score_v3 / t.total_v3 ELSE 0 END AS idx_v3,
    CASE WHEN t.total_v4 > 0 THEN c.score_v4 / t.total_v4 ELSE 0 END AS idx_v4,
    NULLIF(
      CASE WHEN t.total_v1 > 0 THEN c.peso_v1 ELSE 0 END
      + CASE WHEN t.total_v2 > 0 THEN c.peso_v2 ELSE 0 END
      + CASE WHEN t.total_v3 > 0 THEN c.peso_v3 ELSE 0 END
      + CASE WHEN t.total_v4 > 0 THEN c.peso_v4 ELSE 0 END, 0
    ) AS active_w_sum
  FROM combined c JOIN totais t ON t.configuracao_id = c.configuracao_id
)
SELECT
  i.unidade_id,
  i.sigla,
  i.nome,
  i.tipo,
  i.score_v1, i.score_v2, i.score_v3, i.score_v4,
  COALESCE(
    ( CASE WHEN i.total_v1 > 0 THEN i.idx_v1 * i.peso_v1 ELSE 0 END
    + CASE WHEN i.total_v2 > 0 THEN i.idx_v2 * i.peso_v2 ELSE 0 END
    + CASE WHEN i.total_v3 > 0 THEN i.idx_v3 * i.peso_v3 ELSE 0 END
    + CASE WHEN i.total_v4 > 0 THEN i.idx_v4 * i.peso_v4 ELSE 0 END
    ) / i.active_w_sum, 0
  ) AS indice_composto,
  cfg.recurso_bruto,
  cfg.recurso_liquido,
  cfg.pct_total,
  cfg.recurso_liquido * cfg.pct_total / 100.0 AS valor_base,
  COALESCE(
    ( CASE WHEN i.total_v1 > 0 THEN i.idx_v1 * i.peso_v1 ELSE 0 END
    + CASE WHEN i.total_v2 > 0 THEN i.idx_v2 * i.peso_v2 ELSE 0 END
    + CASE WHEN i.total_v3 > 0 THEN i.idx_v3 * i.peso_v3 ELSE 0 END
    + CASE WHEN i.total_v4 > 0 THEN i.idx_v4 * i.peso_v4 ELSE 0 END
    ) / i.active_w_sum, 0
  ) * cfg.recurso_liquido * cfg.pct_total / 100.0 AS valor_estimado
FROM indice i, cfg;

-- -----------------------------------------------------------------------------
-- V1 IMPORTAÇÃO: coluna de modo, tabela raw e view agregada
-- -----------------------------------------------------------------------------

-- Modo de dados V1 na configuração (MANUAL = digitado, IMPORTADO = via CSV)
ALTER TABLE utfprct.matriz_orc_configuracao_base
  ADD COLUMN IF NOT EXISTS v1_modo text NOT NULL DEFAULT 'MANUAL'
    CHECK (v1_modo IN ('MANUAL', 'IMPORTADO'));

-- Tabela para armazenar linhas brutas importadas via CSV
CREATE TABLE IF NOT EXISTS utfprct.matriz_orc_v1_importacao (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuracao_id bigint NOT NULL REFERENCES utfprct.matriz_orc_configuracao_base(id) ON DELETE CASCADE,
  departamento    text,
  professor       text,
  disciplina      text,
  turma           text,
  nome_disc       text,
  cht             numeric(10,2) DEFAULT 0,
  nivel_ensino    text,
  quantidade_alunos integer DEFAULT 0,
  situacao_turma  text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_v1_importacao_cfg
  ON utfprct.matriz_orc_v1_importacao(configuracao_id);

-- View que agrega dados importados no mesmo formato de matriz_orc_v1_unidade
-- Regra de nível: 'G', 'GRAD' ou contém 'gradua' → Graduação; demais → Pós
-- Situações ignoradas: cancelada, inativa, desativada
DROP VIEW IF EXISTS utfprct.vw_matriz_orc_v1_importado;
CREATE VIEW utfprct.vw_matriz_orc_v1_importado AS
SELECT
  i.configuracao_id,
  u.id   AS unidade_id,
  u.sigla,
  u.nome,
  u.tipo,
  SUM(CASE
    WHEN UPPER(TRIM(i.nivel_ensino)) IN ('G','GRAD')
      OR LOWER(i.nivel_ensino) LIKE '%gradua%'
    THEN i.cht ELSE 0
  END) AS carga_horaria_graduacao,
  SUM(CASE
    WHEN UPPER(TRIM(i.nivel_ensino)) NOT IN ('G','GRAD')
     AND LOWER(i.nivel_ensino) NOT LIKE '%gradua%'
    THEN i.cht ELSE 0
  END) AS carga_horaria_pos,
  SUM(CASE
    WHEN UPPER(TRIM(i.nivel_ensino)) IN ('G','GRAD')
      OR LOWER(i.nivel_ensino) LIKE '%gradua%'
    THEN i.quantidade_alunos ELSE 0
  END) AS alunos_graduacao,
  SUM(CASE
    WHEN UPPER(TRIM(i.nivel_ensino)) NOT IN ('G','GRAD')
     AND LOWER(i.nivel_ensino) NOT LIKE '%gradua%'
    THEN i.quantidade_alunos ELSE 0
  END) AS alunos_pos,
  1.0::numeric AS peso_unidade
FROM utfprct.matriz_orc_v1_importacao i
JOIN utfprct.matriz_orc_unidades u
  ON UPPER(TRIM(u.sigla)) = UPPER(TRIM(i.departamento))
WHERE LOWER(COALESCE(i.situacao_turma, '')) NOT IN ('cancelada','inativa','desativada')
GROUP BY i.configuracao_id, u.id, u.sigla, u.nome, u.tipo;

COMMIT;
